const constants = {
	FETCH_RUNS: "FETCH_RUNS",
	SET_RUNS: "SET_RUNS",
	SET_SELECTED_RUN: "SET_SELECTED_RUN",
	CLEAR_SELECTED_RUN: "CLEAR_SELECTED_RUN",
	CANCEL_FETCHING: "CANCEL_FETCHING"
}

export default constants